version: "3"
services:
  firebase:
    build: .
    volumes:
      - ./:/usr/src/workspace
    ports:
      - 3000:3000
      - 4000:4000 # Emulator Suite UI
      - 5001:5001 # Clound Functions
      - 8080:8080 # firestore
      - 9000:9000 # database
      - 9099:9099 # Clound Functions
      - 9005:9005 # auth callback
    working_dir: /usr/src/workspace
    # command: sh -c "cd functions/ && npm run serve:watch"
    tty: true