const allAliasesValue = ['fifth', 'suspended fourth', 'suspended fourth seventh', 'augmented', 'major seventh flat sixth', 'augmented seventh', 'major', 'major seventh', 'dominant seventh', 'sixth', 'major seventh sharp eleventh', 'lydian dominant seventh', 'minor augmented', 'minor', 'minor/major seventh', 'minor seventh', 'minor sixth', 'diminished', 'half-diminished', 'diminished seventh', 'dominant sharp ninth', 'suspended second', 'eleventh', 'major ninth', 'dominant ninth', 'sixth/ninth', 'major thirteenth', 'dominant thirteenth', 'major sharp eleventh (lydian)', 'minor/major ninth', 'minor ninth', 'minor thirteenth', 'minor eleventh', 'suspended fourth flat ninth', 'altered', 'dominant flat ninth'] as const;
export type allAliases = typeof allAliasesValue[number];

export const defaultAliases: { [key in allAliases]: number } = {
    "fifth": 0,
    "suspended fourth": 0,
    "suspended fourth seventh": 0,
    "augmented": 0,
    "major seventh flat sixth": 0,
    "augmented seventh": 0,
    "major": 2,
    "major seventh": 3,
    "dominant seventh": 0,
    "sixth": 0,
    "major seventh sharp eleventh": 3,
    "lydian dominant seventh": 0,
    "minor augmented": 0,
    "minor": 0,
    "minor/major seventh": 2,
    "minor seventh": 0,
    "minor sixth": 0,
    "diminished": 0,
    "half-diminished": 0,
    "diminished seventh": 0,
    "dominant sharp ninth": 0,
    "suspended second": 0,
    "eleventh": 0,
    "major ninth": 0,
    "dominant ninth": 0,
    "sixth/ninth": 1,
    "major thirteenth": 0,
    "dominant thirteenth": 0,
    "major sharp eleventh (lydian)": 0,
    "minor/major ninth": 0,
    "minor ninth": 0,
    "minor thirteenth": 0,
    "minor eleventh": 0,
    "suspended fourth flat ninth": 3,
    "altered": 0,
    "dominant flat ninth": 0
}